on:
  push:
    branches:
      - main
      - 'releases/**'

    # 具体的な実行内容を定義
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run-name: Lint Check
        run: yarn run lint

      - run-name: Type Check
        run: yarn run tsc
