name: Yarn CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    # 具体的な実行内容を定義
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Lint Check
        run: yarn run lint
      - name: Type Check
        run: yarn run tsc
# CItest
