name: Yarn CI

# 実行トリガーの設定
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

    # 具体的な実行内容を定義
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install

      - name: Lint check
        run: yarn lint

      - name: tsc check
        run: yarn tsc
